require_relative './merge_request.rb'
require_relative './pull_request.rb'
require_relative './local_code.rb'
require_relative './highline_cli.rb'

module GitHelper
  class GitLabMergeRequest
    def create
      process_project.create({
        base_branch: base_branch,
        new_title: new_code_request_title
      })
    end

    def merge
      process_project.merge
    end

    private def process_project
      if local_code.github_repo? # GitHub remotes are found
        # If GitLab remotes are also found, ask for clarification, else proceed with GitHub
        local_code.gitlab_project? ? ask_for_clarification : github_pull_request
      elsif local_code.gitlab_project? # Only GitLab remotes are found
        gitlab_merge_request
      else # Neither GitHub nor GitLab remotes are found
        raise StandardError 'Could not locate GitHub or GitLab remote URLs.'
      end
    end

    private def ask_for_clarification
      resp = cli.conflicting_remote_clarification
      if resp.include?('github')
        github_pull_request
      elsif resp.include?('gitlab')
        gitlab_merge_request
      else
        raise StandardError 'The answer we received was not parseable.'
      end
    end

    private def cli
      @cli ||= GitHelper::HighlineCli.new
    end

    private def local_code
      @local_code ||= GitHelper::LocalCode.new
    end

    private def github_pull_request
      @github_pull_request ||= GitHelper::GitHubPullRequest.new({
        local_repo: local_project,
        local_branch: local_branch
      })
    end

    private def gitlab_merge_request
      @gitlab_merge_request ||= GitHelper::GitLabMergeRequest.new({
        local_repo: local_project,
        local_branch: local_branch
      })
    end

    private def local_project
      @local_project ||= local_code.name
    end

    private def local_branch
      @local_branch ||= local_code.branch
    end

    private def base_branch
      @base_branch ||= if cli.base_branch_default?(default_branch)
                         default_branch
                       else
                         cli.base_branch
                       end
    end

    private def autogenerated_title
      @autogenerated_title ||= local_code.generate_title(local_branch)
    end

    private def new_code_request_title
      @new_mr_title ||= if cli.accept_autogenerated_title?(autogenerated_title)
                          autogenerated_title
                        else
                          cli.title
                        end
    end
  end
end
