name: GitLeaks

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  gitleaks:
    uses: emmahsax/reusable-github-actions-workflows/.github/workflows/gitleaks.yml@test
    with:
      gitleaks_config_regexes: "[
        'QPHNXYfNwA1m1LTF7c8xY8pfj5t13vzb0GkA3ZoU',
        'tEBvYBpZi4OIRtS43mLpjLdR6Sp14xSbMZgBgNsv'
      ]"
